[context.production.build]
  command = "echo production"

[context.deploy-preview.build]
  command = "echo deploy-preview"

[context.branch-deploy.build]
  command = "echo branch-deploy"
  
[context.test-contexts.build]
  command = "echo test-context branch"

[[context.test-contexts.plugins]]
  package = "netlify-plugin-a11y"
